// Generated by dagger.internal.codegen.ComponentProcessor (https://google.github.io/dagger).
package com.legendsbsc.wallet.ui;

import com.legendsbsc.wallet.viewmodel.AddTokenViewModelFactory;
import dagger.MembersInjector;
import javax.inject.Provider;

public final class AddTokenActivity_MembersInjector implements MembersInjector<AddTokenActivity> {
  private final Provider<AddTokenViewModelFactory> addTokenViewModelFactoryProvider;

  public AddTokenActivity_MembersInjector(
      Provider<AddTokenViewModelFactory> addTokenViewModelFactoryProvider) {
    assert addTokenViewModelFactoryProvider != null;
    this.addTokenViewModelFactoryProvider = addTokenViewModelFactoryProvider;
  }

  public static MembersInjector<AddTokenActivity> create(
      Provider<AddTokenViewModelFactory> addTokenViewModelFactoryProvider) {
    return new AddTokenActivity_MembersInjector(addTokenViewModelFactoryProvider);
  }

  @Override
  public void injectMembers(AddTokenActivity instance) {
    if (instance == null) {
      throw new NullPointerException("Cannot inject members into a null reference");
    }
    instance.addTokenViewModelFactory = addTokenViewModelFactoryProvider.get();
  }

  public static void injectAddTokenViewModelFactory(
      AddTokenActivity instance,
      Provider<AddTokenViewModelFactory> addTokenViewModelFactoryProvider) {
    instance.addTokenViewModelFactory = addTokenViewModelFactoryProvider.get();
  }
}
