// Generated by dagger.internal.codegen.ComponentProcessor (https://google.github.io/dagger).
package com.legendsbsc.wallet.ui;

import com.legendsbsc.wallet.viewmodel.ConfirmationViewModelFactory;
import dagger.MembersInjector;
import javax.inject.Provider;

public final class ConfirmationActivity_MembersInjector
    implements MembersInjector<ConfirmationActivity> {
  private final Provider<ConfirmationViewModelFactory> confirmationViewModelFactoryProvider;

  public ConfirmationActivity_MembersInjector(
      Provider<ConfirmationViewModelFactory> confirmationViewModelFactoryProvider) {
    assert confirmationViewModelFactoryProvider != null;
    this.confirmationViewModelFactoryProvider = confirmationViewModelFactoryProvider;
  }

  public static MembersInjector<ConfirmationActivity> create(
      Provider<ConfirmationViewModelFactory> confirmationViewModelFactoryProvider) {
    return new ConfirmationActivity_MembersInjector(confirmationViewModelFactoryProvider);
  }

  @Override
  public void injectMembers(ConfirmationActivity instance) {
    if (instance == null) {
      throw new NullPointerException("Cannot inject members into a null reference");
    }
    instance.confirmationViewModelFactory = confirmationViewModelFactoryProvider.get();
  }

  public static void injectConfirmationViewModelFactory(
      ConfirmationActivity instance,
      Provider<ConfirmationViewModelFactory> confirmationViewModelFactoryProvider) {
    instance.confirmationViewModelFactory = confirmationViewModelFactoryProvider.get();
  }
}
