// Generated by dagger.internal.codegen.ComponentProcessor (https://google.github.io/dagger).
package com.legendsbsc.wallet.ui;

import com.legendsbsc.wallet.viewmodel.GasSettingsViewModelFactory;
import dagger.MembersInjector;
import javax.inject.Provider;

public final class GasSettingsActivity_MembersInjector
    implements MembersInjector<GasSettingsActivity> {
  private final Provider<GasSettingsViewModelFactory> viewModelFactoryProvider;

  public GasSettingsActivity_MembersInjector(
      Provider<GasSettingsViewModelFactory> viewModelFactoryProvider) {
    assert viewModelFactoryProvider != null;
    this.viewModelFactoryProvider = viewModelFactoryProvider;
  }

  public static MembersInjector<GasSettingsActivity> create(
      Provider<GasSettingsViewModelFactory> viewModelFactoryProvider) {
    return new GasSettingsActivity_MembersInjector(viewModelFactoryProvider);
  }

  @Override
  public void injectMembers(GasSettingsActivity instance) {
    if (instance == null) {
      throw new NullPointerException("Cannot inject members into a null reference");
    }
    instance.viewModelFactory = viewModelFactoryProvider.get();
  }

  public static void injectViewModelFactory(
      GasSettingsActivity instance,
      Provider<GasSettingsViewModelFactory> viewModelFactoryProvider) {
    instance.viewModelFactory = viewModelFactoryProvider.get();
  }
}
