// Generated by dagger.internal.codegen.ComponentProcessor (https://google.github.io/dagger).
package com.legendsbsc.wallet.ui;

import com.legendsbsc.wallet.viewmodel.ImportWalletViewModelFactory;
import dagger.MembersInjector;
import javax.inject.Provider;

public final class ImportWalletActivity_MembersInjector
    implements MembersInjector<ImportWalletActivity> {
  private final Provider<ImportWalletViewModelFactory> importWalletViewModelFactoryProvider;

  public ImportWalletActivity_MembersInjector(
      Provider<ImportWalletViewModelFactory> importWalletViewModelFactoryProvider) {
    assert importWalletViewModelFactoryProvider != null;
    this.importWalletViewModelFactoryProvider = importWalletViewModelFactoryProvider;
  }

  public static MembersInjector<ImportWalletActivity> create(
      Provider<ImportWalletViewModelFactory> importWalletViewModelFactoryProvider) {
    return new ImportWalletActivity_MembersInjector(importWalletViewModelFactoryProvider);
  }

  @Override
  public void injectMembers(ImportWalletActivity instance) {
    if (instance == null) {
      throw new NullPointerException("Cannot inject members into a null reference");
    }
    instance.importWalletViewModelFactory = importWalletViewModelFactoryProvider.get();
  }

  public static void injectImportWalletViewModelFactory(
      ImportWalletActivity instance,
      Provider<ImportWalletViewModelFactory> importWalletViewModelFactoryProvider) {
    instance.importWalletViewModelFactory = importWalletViewModelFactoryProvider.get();
  }
}
