// Generated by dagger.internal.codegen.ComponentProcessor (https://google.github.io/dagger).
package com.legendsbsc.wallet.ui;

import com.legendsbsc.wallet.repository.EthereumNetworkRepositoryType;
import dagger.MembersInjector;
import javax.inject.Provider;

public final class MyAddressActivity_MembersInjector implements MembersInjector<MyAddressActivity> {
  private final Provider<EthereumNetworkRepositoryType> ethereumNetworkRepositoryProvider;

  public MyAddressActivity_MembersInjector(
      Provider<EthereumNetworkRepositoryType> ethereumNetworkRepositoryProvider) {
    assert ethereumNetworkRepositoryProvider != null;
    this.ethereumNetworkRepositoryProvider = ethereumNetworkRepositoryProvider;
  }

  public static MembersInjector<MyAddressActivity> create(
      Provider<EthereumNetworkRepositoryType> ethereumNetworkRepositoryProvider) {
    return new MyAddressActivity_MembersInjector(ethereumNetworkRepositoryProvider);
  }

  @Override
  public void injectMembers(MyAddressActivity instance) {
    if (instance == null) {
      throw new NullPointerException("Cannot inject members into a null reference");
    }
    instance.ethereumNetworkRepository = ethereumNetworkRepositoryProvider.get();
  }

  public static void injectEthereumNetworkRepository(
      MyAddressActivity instance,
      Provider<EthereumNetworkRepositoryType> ethereumNetworkRepositoryProvider) {
    instance.ethereumNetworkRepository = ethereumNetworkRepositoryProvider.get();
  }
}
