// Generated by dagger.internal.codegen.ComponentProcessor (https://google.github.io/dagger).
package com.legendsbsc.wallet.ui;

import com.legendsbsc.wallet.viewmodel.SplashViewModelFactory;
import dagger.MembersInjector;
import javax.inject.Provider;

public final class SplashActivity_MembersInjector implements MembersInjector<SplashActivity> {
  private final Provider<SplashViewModelFactory> splashViewModelFactoryProvider;

  public SplashActivity_MembersInjector(
      Provider<SplashViewModelFactory> splashViewModelFactoryProvider) {
    assert splashViewModelFactoryProvider != null;
    this.splashViewModelFactoryProvider = splashViewModelFactoryProvider;
  }

  public static MembersInjector<SplashActivity> create(
      Provider<SplashViewModelFactory> splashViewModelFactoryProvider) {
    return new SplashActivity_MembersInjector(splashViewModelFactoryProvider);
  }

  @Override
  public void injectMembers(SplashActivity instance) {
    if (instance == null) {
      throw new NullPointerException("Cannot inject members into a null reference");
    }
    instance.splashViewModelFactory = splashViewModelFactoryProvider.get();
  }

  public static void injectSplashViewModelFactory(
      SplashActivity instance, Provider<SplashViewModelFactory> splashViewModelFactoryProvider) {
    instance.splashViewModelFactory = splashViewModelFactoryProvider.get();
  }
}
