// Generated by dagger.internal.codegen.ComponentProcessor (https://google.github.io/dagger).
package com.legendsbsc.wallet.ui;

import com.legendsbsc.wallet.viewmodel.TokensViewModelFactory;
import dagger.MembersInjector;
import javax.inject.Provider;

public final class TokensActivity_MembersInjector implements MembersInjector<TokensActivity> {
  private final Provider<TokensViewModelFactory> transactionsViewModelFactoryProvider;

  public TokensActivity_MembersInjector(
      Provider<TokensViewModelFactory> transactionsViewModelFactoryProvider) {
    assert transactionsViewModelFactoryProvider != null;
    this.transactionsViewModelFactoryProvider = transactionsViewModelFactoryProvider;
  }

  public static MembersInjector<TokensActivity> create(
      Provider<TokensViewModelFactory> transactionsViewModelFactoryProvider) {
    return new TokensActivity_MembersInjector(transactionsViewModelFactoryProvider);
  }

  @Override
  public void injectMembers(TokensActivity instance) {
    if (instance == null) {
      throw new NullPointerException("Cannot inject members into a null reference");
    }
    instance.transactionsViewModelFactory = transactionsViewModelFactoryProvider.get();
  }

  public static void injectTransactionsViewModelFactory(
      TokensActivity instance,
      Provider<TokensViewModelFactory> transactionsViewModelFactoryProvider) {
    instance.transactionsViewModelFactory = transactionsViewModelFactoryProvider.get();
  }
}
