// Generated by dagger.internal.codegen.ComponentProcessor (https://google.github.io/dagger).
package com.legendsbsc.wallet.ui;

import com.legendsbsc.wallet.viewmodel.TransactionDetailViewModelFactory;
import dagger.MembersInjector;
import javax.inject.Provider;

public final class TransactionDetailActivity_MembersInjector
    implements MembersInjector<TransactionDetailActivity> {
  private final Provider<TransactionDetailViewModelFactory>
      transactionDetailViewModelFactoryProvider;

  public TransactionDetailActivity_MembersInjector(
      Provider<TransactionDetailViewModelFactory> transactionDetailViewModelFactoryProvider) {
    assert transactionDetailViewModelFactoryProvider != null;
    this.transactionDetailViewModelFactoryProvider = transactionDetailViewModelFactoryProvider;
  }

  public static MembersInjector<TransactionDetailActivity> create(
      Provider<TransactionDetailViewModelFactory> transactionDetailViewModelFactoryProvider) {
    return new TransactionDetailActivity_MembersInjector(transactionDetailViewModelFactoryProvider);
  }

  @Override
  public void injectMembers(TransactionDetailActivity instance) {
    if (instance == null) {
      throw new NullPointerException("Cannot inject members into a null reference");
    }
    instance.transactionDetailViewModelFactory = transactionDetailViewModelFactoryProvider.get();
  }

  public static void injectTransactionDetailViewModelFactory(
      TransactionDetailActivity instance,
      Provider<TransactionDetailViewModelFactory> transactionDetailViewModelFactoryProvider) {
    instance.transactionDetailViewModelFactory = transactionDetailViewModelFactoryProvider.get();
  }
}
