// Generated by dagger.internal.codegen.ComponentProcessor (https://google.github.io/dagger).
package com.legendsbsc.wallet.ui;

import com.legendsbsc.wallet.viewmodel.TransactionsViewModelFactory;
import dagger.MembersInjector;
import javax.inject.Provider;

public final class TransactionsActivity_MembersInjector
    implements MembersInjector<TransactionsActivity> {
  private final Provider<TransactionsViewModelFactory> transactionsViewModelFactoryProvider;

  public TransactionsActivity_MembersInjector(
      Provider<TransactionsViewModelFactory> transactionsViewModelFactoryProvider) {
    assert transactionsViewModelFactoryProvider != null;
    this.transactionsViewModelFactoryProvider = transactionsViewModelFactoryProvider;
  }

  public static MembersInjector<TransactionsActivity> create(
      Provider<TransactionsViewModelFactory> transactionsViewModelFactoryProvider) {
    return new TransactionsActivity_MembersInjector(transactionsViewModelFactoryProvider);
  }

  @Override
  public void injectMembers(TransactionsActivity instance) {
    if (instance == null) {
      throw new NullPointerException("Cannot inject members into a null reference");
    }
    instance.transactionsViewModelFactory = transactionsViewModelFactoryProvider.get();
  }

  public static void injectTransactionsViewModelFactory(
      TransactionsActivity instance,
      Provider<TransactionsViewModelFactory> transactionsViewModelFactoryProvider) {
    instance.transactionsViewModelFactory = transactionsViewModelFactoryProvider.get();
  }
}
