// Generated by dagger.internal.codegen.ComponentProcessor (https://google.github.io/dagger).
package com.legendsbsc.wallet.ui;

import com.legendsbsc.wallet.viewmodel.WalletsViewModelFactory;
import dagger.MembersInjector;
import javax.inject.Provider;

public final class WalletsActivity_MembersInjector implements MembersInjector<WalletsActivity> {
  private final Provider<WalletsViewModelFactory> walletsViewModelFactoryProvider;

  public WalletsActivity_MembersInjector(
      Provider<WalletsViewModelFactory> walletsViewModelFactoryProvider) {
    assert walletsViewModelFactoryProvider != null;
    this.walletsViewModelFactoryProvider = walletsViewModelFactoryProvider;
  }

  public static MembersInjector<WalletsActivity> create(
      Provider<WalletsViewModelFactory> walletsViewModelFactoryProvider) {
    return new WalletsActivity_MembersInjector(walletsViewModelFactoryProvider);
  }

  @Override
  public void injectMembers(WalletsActivity instance) {
    if (instance == null) {
      throw new NullPointerException("Cannot inject members into a null reference");
    }
    instance.walletsViewModelFactory = walletsViewModelFactoryProvider.get();
  }

  public static void injectWalletsViewModelFactory(
      WalletsActivity instance, Provider<WalletsViewModelFactory> walletsViewModelFactoryProvider) {
    instance.walletsViewModelFactory = walletsViewModelFactoryProvider.get();
  }
}
